export const ErrorCodes = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  INVALID_REQUEST_ORIGIN: "INVALID_REQUEST_ORIGIN",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  INVALID_VOUCHER: "INVALID_VOUCHER",
  VOUCHER_NOT_APPLICABLE: "VOUCHER_NOT_APPLICABLE",
  VOUCHER_USAGE_EXCEEDED: "VOUCHER_USAGE_EXCEEDED",
  VOUCHER_EXPIRED: "VOUCHER_EXPIRED",
  VOUCHER_STACKING_NOT_ALLOWED: "VOUCHER_STACKING_NOT_ALLOWED",
  CHECKOUT_IDEMPOTENCY_CONFLICT: "CHECKOUT_IDEMPOTENCY_CONFLICT",
  PAYMENT_PROOF_INVALID: "PAYMENT_PROOF_INVALID",
  PAYMENT_ALREADY_CONFIRMED: "PAYMENT_ALREADY_CONFIRMED",
  ORDER_STATUS_TRANSITION_INVALID: "ORDER_STATUS_TRANSITION_INVALID",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
