export type AccessLevel = "Public" | "Customer" | "Admin";
export type HttpMethod = "GET" | "POST" | "PATCH" | "DELETE";

export interface DeveloperDocsNavItem {
  id: string;
  label: string;
}

export interface DeveloperDocsStat {
  label: string;
  value: string;
  description: string;
}

export interface QuickstartStep {
  title: string;
  description: string;
}

export interface EnvironmentVariableDoc {
  name: string;
  defaultValue: string;
  notes: string;
}

export interface ApiMethodDoc {
  method: HttpMethod;
  access: AccessLevel;
  request: string;
  response: string;
  notes: string;
}

export interface ApiEndpointDoc {
  path: string;
  source: string;
  summary: string;
  methods: ApiMethodDoc[];
}

export interface ApiDomainDoc {
  id: string;
  title: string;
  description: string;
  endpoints: ApiEndpointDoc[];
}

export interface ServerFunctionDoc {
  name: string;
  signature: string;
  notes: string;
}

export interface ServerModuleDoc {
  title: string;
  path: string;
  summary: string;
  functions: ServerFunctionDoc[];
}

export interface HookDoc {
  name: string;
  path: string;
  summary: string;
  returns: string[];
}

export interface ClientHelperDoc {
  title: string;
  path: string;
  summary: string;
  functions: string[];
}

export interface ContractGroupDoc {
  title: string;
  path: string;
  summary: string;
  items: string[];
}

export interface CodeExampleDoc {
  title: string;
  language: string;
  description: string;
  code: string;
}

export const developerDocsNav: DeveloperDocsNavItem[] = [
  { id: "overview", label: "Overview" },
  { id: "quickstart", label: "Quickstart" },
  { id: "environment", label: "Environment" },
  { id: "architecture", label: "Architecture" },
  { id: "api-reference", label: "API Reference" },
  { id: "server-modules", label: "Server Modules" },
  { id: "domain-helpers", label: "Domain Helpers" },
  { id: "hooks", label: "Hooks" },
  { id: "client-helpers", label: "Client Helpers" },
  { id: "contracts", label: "Contracts" },
  { id: "examples", label: "Examples" },
  { id: "operations", label: "Operations" },
];

export const quickstartSteps: QuickstartStep[] = [
  {
    title: "Bootstrap the workspace",
    description:
      "Copy `.env.local.example` into `.env.local`, install dependencies with `npm ci`, and confirm PostgreSQL is reachable from `DATABASE_URL`.",
  },
  {
    title: "Prepare Prisma and seed data",
    description:
      "Run `npm run db:generate`, `npm run db:migrate`, and `npm run db:seed` to materialize the schema, default settings, catalog fixtures, and admin account.",
  },
  {
    title: "Start the engine",
    description:
      "Run `npm run dev` for local development or `npm run build && npm run start` to verify the production build locally.",
  },
  {
    title: "Build on the engine, not around it",
    description:
      "New storefronts should consume shared contracts, server modules, and client helpers. Re-theme and replace UI surfaces without forking core business logic.",
  },
];

export const quickstartCommand = `npm ci
npm run db:generate
npm run db:migrate
npm run db:seed
npm run dev`;

export const environmentVariables: EnvironmentVariableDoc[] = [
  {
    name: "DATABASE_URL",
    defaultValue:
      "postgresql://postgres:postgres@localhost:5432/ecommerce_engine?schema=public",
    notes: "Required. Prisma datasource for all server modules.",
  },
  {
    name: "AUTH_SECRET",
    defaultValue: "change-this-before-deploying",
    notes: "Required. Signs the httpOnly session cookie.",
  },
  {
    name: "APP_URL",
    defaultValue: "http://localhost:3000",
    notes: "Required. Used by runtime config, callbacks, and deployment assumptions.",
  },
  {
    name: "UPLOAD_STORAGE_DRIVER",
    defaultValue: "mock",
    notes: "Current baseline supports `mock`, `local`, and `s3`, but payment proof flow is still mock-first.",
  },
  {
    name: "UPLOAD_STORAGE_BASE_URL",
    defaultValue: "http://localhost:3000/uploads",
    notes: "Base URL for upload locations when the app moves beyond mock proof URLs.",
  },
  {
    name: "DEFAULT_TIMEZONE",
    defaultValue: "Asia/Jakarta",
    notes: "Fallback timezone for instructions, formatting, and seed defaults.",
  },
  {
    name: "DEFAULT_CURRENCY",
    defaultValue: "IDR",
    notes: "Fallback currency used by checkout and order snapshots.",
  },
  {
    name: "DEFAULT_LOCALE",
    defaultValue: "id-ID",
    notes: "Locale baseline for formatting and presentation defaults.",
  },
  {
    name: "SEED_ADMIN_EMAIL",
    defaultValue: "admin@example.com",
    notes: "Local bootstrap admin account generated by `npm run db:seed`.",
  },
  {
    name: "SEED_ADMIN_NAME",
    defaultValue: "Store Admin",
    notes: "Display name for the seeded admin user.",
  },
  {
    name: "SEED_ADMIN_PHONE",
    defaultValue: "+6280000000000",
    notes: "Phone number persisted for the seeded admin user.",
  },
  {
    name: "SEED_ADMIN_PASSWORD",
    defaultValue: "Admin12345!",
    notes: "Local-only bootstrap credential. Replace immediately outside local development.",
  },
];

export const architectureLayers = [
  {
    title: "App Router UI",
    path: "app/",
    description:
      "Pages, route handlers, and deployable surfaces. Use this layer for presentation, composition, and SSR boundaries.",
  },
  {
    title: "Server Modules",
    path: "src/server/",
    description:
      "Reusable business modules for auth, catalog, cart, checkout, orders, payments, promotions, inventory, settings, audit, and supporting services.",
  },
  {
    title: "Shared Contracts",
    path: "src/shared/contracts/",
    description:
      "Zod schemas, DTOs, route param validation, API envelopes, and error codes. This is the source of truth for request and response shapes.",
  },
  {
    title: "Client Integration",
    path: "src/lib/ and src/hooks/",
    description:
      "Thin wrappers for fetch, mutation, and local UI state. Business rules should stay in `src/server`, not here.",
  },
  {
    title: "Data Layer",
    path: "prisma/",
    description:
      "Prisma schema, migrations, and seed logic. This layer anchors inventory, payments, promotions, settings, and order history.",
  },
];

export const apiDomains: ApiDomainDoc[] = [
  {
    id: "public-commerce",
    title: "Public Commerce APIs",
    description:
      "Public or low-friction endpoints used by storefront browsing, search, and voucher evaluation.",
    endpoints: [
      {
        path: "/api/categories",
        source: "app/api/categories/route.ts",
        summary: "List active public categories for storefront filters and landing pages.",
        methods: [
          {
            method: "GET",
            access: "Public",
            request: "No body. Same-origin request.",
            response: "ApiEnvelope<Category[]>",
            notes: "Used by the storefront categories route and product filter surfaces.",
          },
        ],
      },
      {
        path: "/api/products",
        source: "app/api/products/route.ts",
        summary: "Paginated public product listing with search, category, sort, and price filters.",
        methods: [
          {
            method: "GET",
            access: "Public",
            request: "Query = ProductListQuery",
            response: "ApiEnvelope<ProductListResult> with pagination meta",
            notes:
              "Supports `page`, `pageSize`, `category`, `search`, `sort`, `minPrice`, and `maxPrice`.",
          },
        ],
      },
      {
        path: "/api/products/[slug]",
        source: "app/api/products/[slug]/route.ts",
        summary: "Load a single public product detail with variant and option metadata.",
        methods: [
          {
            method: "GET",
            access: "Public",
            request: "Route param `slug`",
            response: "ApiEnvelope<ProductDetailRecord>",
            notes: "Backs storefront product detail pages and add-to-cart preparation.",
          },
        ],
      },
      {
        path: "/api/vouchers/validate",
        source: "app/api/vouchers/validate/route.ts",
        summary: "Validate voucher codes without placing an order.",
        methods: [
          {
            method: "POST",
            access: "Public",
            request: "Body = ValidateVoucherDto",
            response: "ApiEnvelope<VoucherValidationResult>",
            notes: "Used by checkout preview and admin verification flows.",
          },
        ],
      },
    ],
  },
  {
    id: "customer-session",
    title: "Customer Session and Checkout APIs",
    description:
      "Cookie-backed customer routes for auth, cart, addresses, checkout preview, orders, and payment proof.",
    endpoints: [
      {
        path: "/api/auth/register",
        source: "app/api/auth/register/route.ts",
        summary: "Create a customer account and issue a session cookie.",
        methods: [
          {
            method: "POST",
            access: "Public",
            request: "Body = RegisterDto",
            response: "ApiEnvelope<{ user: AuthSessionRecord }>",
            notes: "Also claims any existing guest cart into the newly created user session.",
          },
        ],
      },
      {
        path: "/api/auth/login",
        source: "app/api/auth/login/route.ts",
        summary: "Authenticate a customer or admin and issue a session cookie.",
        methods: [
          {
            method: "POST",
            access: "Public",
            request: "Body = LoginDto",
            response: "ApiEnvelope<{ user: AuthSessionRecord }>",
            notes: "Merges guest cart state into the authenticated account when needed.",
          },
        ],
      },
      {
        path: "/api/auth/logout",
        source: "app/api/auth/logout/route.ts",
        summary: "Clear the session cookie and return a success envelope.",
        methods: [
          {
            method: "POST",
            access: "Customer",
            request: "No body",
            response: "ApiEnvelope<{ success: true }>",
            notes: "Same-origin cookie mutation. Origin checks still apply.",
          },
        ],
      },
      {
        path: "/api/me",
        source: "app/api/me/route.ts",
        summary: "Read or update the currently authenticated user's profile.",
        methods: [
          {
            method: "GET",
            access: "Customer",
            request: "No body",
            response: "ApiEnvelope<AuthSessionRecord>",
            notes: "Used by `useSession`, profile pages, and auth-aware shells.",
          },
          {
            method: "PATCH",
            access: "Customer",
            request: "Body = UpdateProfileDto",
            response: "ApiEnvelope<ProfileRecord>",
            notes: "Only mutable profile fields are updated.",
          },
        ],
      },
      {
        path: "/api/addresses",
        source: "app/api/addresses/route.ts",
        summary: "Manage saved customer addresses.",
        methods: [
          {
            method: "GET",
            access: "Customer",
            request: "No body",
            response: "ApiEnvelope<AddressRecord[]>",
            notes: "Returns only addresses owned by the current session user.",
          },
          {
            method: "POST",
            access: "Customer",
            request: "Body = CreateAddressDto",
            response: "ApiEnvelope<AddressRecord>",
            notes: "Default address handling is enforced in the server module.",
          },
        ],
      },
      {
        path: "/api/addresses/[id]",
        source: "app/api/addresses/[id]/route.ts",
        summary: "Update or delete one saved address.",
        methods: [
          {
            method: "PATCH",
            access: "Customer",
            request: "Route param `id`, body = UpdateAddressDto",
            response: "ApiEnvelope<AddressRecord>",
            notes:
              "Owner-only. Route params are validated with shared route param schemas.",
          },
          {
            method: "DELETE",
            access: "Customer",
            request: "Route param `id`",
            response: "ApiEnvelope<{ deleted: boolean }>",
            notes:
              "Owner-only deletion. Default address promotion is handled server-side.",
          },
        ],
      },
      {
        path: "/api/cart",
        source: "app/api/cart/route.ts",
        summary: "Read the active cart or clear it entirely.",
        methods: [
          {
            method: "GET",
            access: "Customer",
            request: "No body",
            response: "ApiEnvelope<CartSnapshot>",
            notes: "Supports guest token generation when the request is unauthenticated.",
          },
          {
            method: "DELETE",
            access: "Customer",
            request: "No body",
            response: "ApiEnvelope<CartSnapshot>",
            notes: "Useful for E2E reset and explicit cart clearing flows.",
          },
        ],
      },
      {
        path: "/api/cart/items",
        source: "app/api/cart/items/route.ts",
        summary: "Add an item into the active cart.",
        methods: [
          {
            method: "POST",
            access: "Customer",
            request: "Body = AddCartItemDto",
            response: "ApiEnvelope<CartSnapshot>",
            notes: "Validates product activity, variant identity, and available stock.",
          },
        ],
      },
      {
        path: "/api/cart/items/[itemId]",
        source: "app/api/cart/items/[itemId]/route.ts",
        summary: "Adjust or remove an existing cart line.",
        methods: [
          {
            method: "PATCH",
            access: "Customer",
            request: "Route param `itemId`, body = UpdateCartItemDto",
            response: "ApiEnvelope<CartSnapshot>",
            notes: "Re-checks available stock before changing quantity.",
          },
          {
            method: "DELETE",
            access: "Customer",
            request: "Route param `itemId`",
            response: "ApiEnvelope<CartSnapshot>",
            notes: "Owner-only. Keeps cart session cookies in sync.",
          },
        ],
      },
      {
        path: "/api/checkout/preview",
        source: "app/api/checkout/preview/route.ts",
        summary: "Build a live quote from the active cart without placing an order.",
        methods: [
          {
            method: "POST",
            access: "Customer",
            request: "Body = CheckoutPreviewDto",
            response: "ApiEnvelope<CheckoutPreviewResult>",
            notes: "Uses the same formula engine as final order placement.",
          },
        ],
      },
      {
        path: "/api/orders",
        source: "app/api/orders/route.ts",
        summary: "List customer orders or place a new order from the active cart.",
        methods: [
          {
            method: "GET",
            access: "Customer",
            request: "Query = OrderListQuery",
            response: "ApiEnvelope<OrderListResult> with pagination meta",
            notes: "Owner-scoped order listing.",
          },
          {
            method: "POST",
            access: "Customer",
            request:
              "Body = PlaceOrderDto, header `idempotency-key` recommended",
            response: "ApiEnvelope<OrderDetailRecord>",
            notes:
              "Creates order, payment, reservations, promotion usage, and audit log entries in one transactional flow.",
          },
        ],
      },
      {
        path: "/api/orders/[orderId]",
        source: "app/api/orders/[orderId]/route.ts",
        summary:
          "Fetch one customer-owned order with payments, proofs, items, and reservations.",
        methods: [
          {
            method: "GET",
            access: "Customer",
            request: "Route param `orderId`",
            response: "ApiEnvelope<OrderDetailRecord>",
            notes:
              "Owner-only. Used by order detail and payment review follow-up screens.",
          },
        ],
      },
      {
        path: "/api/orders/[orderId]/payment-instructions",
        source: "app/api/orders/[orderId]/payment-instructions/route.ts",
        summary: "Return private payment instructions for one order.",
        methods: [
          {
            method: "GET",
            access: "Customer",
            request: "Route param `orderId`",
            response: "ApiEnvelope<PaymentInstructions>",
            notes: "Accessible to the order owner and admins only.",
          },
        ],
      },
      {
        path: "/api/orders/[orderId]/payment-proof",
        source: "app/api/orders/[orderId]/payment-proof/route.ts",
        summary: "Upload a payment proof location for manual transfer review.",
        methods: [
          {
            method: "POST",
            access: "Customer",
            request: "Route param `orderId`, body = UploadPaymentProofDto",
            response: "ApiEnvelope<PaymentRecord>",
            notes:
              "Current baseline accepts HTTPS URLs or `/uploads/` paths, not binary uploads.",
          },
        ],
      },
    ],
  },
  {
    id: "admin-operations",
    title: "Admin Operations APIs",
    description:
      "Admin-only endpoints for dashboarding, catalog, inventory, orders, payments, promotions, settings, users, and audit trails.",
    endpoints: [
      {
        path: "/api/admin/dashboard",
        source: "app/api/admin/dashboard/route.ts",
        summary: "Dashboard summary counts and top-level operational metrics.",
        methods: [
          {
            method: "GET",
            access: "Admin",
            request: "No body",
            response: "ApiEnvelope<AdminDashboardSummary>",
            notes: "Backs the admin homepage metrics cards.",
          },
        ],
      },
      {
        path: "/api/admin/users",
        source: "app/api/admin/users/route.ts",
        summary: "Paginated registry of engine users.",
        methods: [
          {
            method: "GET",
            access: "Admin",
            request: "Query = UserListQuery",
            response: "ApiEnvelope<UserListResult> with pagination meta",
            notes: "Read-only registry for now.",
          },
        ],
      },
      {
        path: "/api/admin/categories",
        source: "app/api/admin/categories/route.ts",
        summary: "List or create product categories.",
        methods: [
          {
            method: "GET",
            access: "Admin",
            request: "No body",
            response: "ApiEnvelope<CategoryMutationRecord[]>",
            notes: "Admin catalog surface for category maintenance.",
          },
          {
            method: "POST",
            access: "Admin",
            request: "Body = CreateCategoryDto",
            response: "ApiEnvelope<CategoryMutationRecord>",
            notes: "Slug uniqueness is enforced in the catalog module.",
          },
        ],
      },
      {
        path: "/api/admin/categories/[id]",
        source: "app/api/admin/categories/[id]/route.ts",
        summary: "Update or delete an admin category.",
        methods: [
          {
            method: "PATCH",
            access: "Admin",
            request: "Route param `id`, body = UpdateCategoryDto",
            response: "ApiEnvelope<CategoryMutationRecord>",
            notes:
              "Uses shared param validation and Prisma-backed uniqueness checks.",
          },
          {
            method: "DELETE",
            access: "Admin",
            request: "Route param `id`",
            response: "ApiEnvelope<{ deleted: boolean }>",
            notes: "Delete is guarded against invalid target ids.",
          },
        ],
      },
      {
        path: "/api/admin/products",
        source: "app/api/admin/products/route.ts",
        summary:
          "List or create full products including option definitions and variants.",
        methods: [
          {
            method: "GET",
            access: "Admin",
            request: "Query = ProductListQuery",
            response: "ApiEnvelope<AdminProductListResult> with pagination meta",
            notes:
              "Admin listing includes richer catalog context than the public listing.",
          },
          {
            method: "POST",
            access: "Admin",
            request: "Body = CreateProductDto",
            response: "ApiEnvelope<{ id: string }>",
            notes:
              "Creates products, option definitions, option values, and variant combinations in one flow.",
          },
        ],
      },
      {
        path: "/api/admin/products/[id]",
        source: "app/api/admin/products/[id]/route.ts",
        summary: "Read, update, or delete a single admin product.",
        methods: [
          {
            method: "GET",
            access: "Admin",
            request: "Route param `id`",
            response: "ApiEnvelope<AdminProductDetailRecord>",
            notes: "Hydrates the admin product editor.",
          },
          {
            method: "PATCH",
            access: "Admin",
            request: "Route param `id`, body = UpdateProductDto",
            response: "ApiEnvelope<ProductRecord>",
            notes:
              "Rebuilds option definitions and variant combinations when needed.",
          },
          {
            method: "DELETE",
            access: "Admin",
            request: "Route param `id`",
            response: "ApiEnvelope<{ deleted: boolean }>",
            notes: "Used by the admin catalog workspace.",
          },
        ],
      },
      {
        path: "/api/admin/orders",
        source: "app/api/admin/orders/route.ts",
        summary: "Admin list of orders with status and search filters.",
        methods: [
          {
            method: "GET",
            access: "Admin",
            request: "Query = OrderListQuery",
            response: "ApiEnvelope<OrderListResult> with pagination meta",
            notes: "Operational order queue.",
          },
        ],
      },
      {
        path: "/api/admin/orders/[id]",
        source: "app/api/admin/orders/[id]/route.ts",
        summary:
          "Admin order detail with items, payments, promotions, and reservations.",
        methods: [
          {
            method: "GET",
            access: "Admin",
            request: "Route param `id`",
            response: "ApiEnvelope<OrderDetailRecord>",
            notes:
              "Primary detail endpoint for support and fulfillment operations.",
          },
        ],
      },
      {
        path: "/api/admin/orders/[id]/status",
        source: "app/api/admin/orders/[id]/status/route.ts",
        summary:
          "Advance or revert order state under server-side transition rules.",
        methods: [
          {
            method: "PATCH",
            access: "Admin",
            request: "Route param `id`, body = UpdateOrderStatusDto",
            response: "ApiEnvelope<OrderDetailRecord>",
            notes:
              "Synchronizes order state, payment state, reservations, stock consumption, and audit logs.",
          },
        ],
      },
      {
        path: "/api/admin/payments/review-queue",
        source: "app/api/admin/payments/review-queue/route.ts",
        summary: "List payments waiting for manual review.",
        methods: [
          {
            method: "GET",
            access: "Admin",
            request: "Query = PaymentReviewQueueQuery",
            response: "ApiEnvelope<PaymentReviewQueueResult> with pagination meta",
            notes: "Backs `/admin/payments`.",
          },
        ],
      },
      {
        path: "/api/admin/payments/[paymentId]/review",
        source: "app/api/admin/payments/[paymentId]/review/route.ts",
        summary: "Confirm or reject a manual transfer proof.",
        methods: [
          {
            method: "POST",
            access: "Admin",
            request: "Route param `paymentId`, body = ReviewPaymentDto",
            response: "ApiEnvelope<PaymentRecord>",
            notes:
              "Also updates the parent order status and writes audit entries.",
          },
        ],
      },
      {
        path: "/api/admin/promotions",
        source: "app/api/admin/promotions/route.ts",
        summary: "List or create promotions and vouchers.",
        methods: [
          {
            method: "GET",
            access: "Admin",
            request: "Query = PromotionListQuery",
            response: "ApiEnvelope<PromotionListResult> with pagination meta",
            notes: "Supports search, type, and active status filters.",
          },
          {
            method: "POST",
            access: "Admin",
            request: "Body = CreatePromotionDto",
            response: "ApiEnvelope<PromotionRecord>",
            notes:
              "Supports `PERCENTAGE`, `FIXED_AMOUNT`, `FREE_PRODUCT`, and `FREE_SHIPPING`.",
          },
        ],
      },
      {
        path: "/api/admin/promotions/[id]",
        source: "app/api/admin/promotions/[id]/route.ts",
        summary: "Update or delete a promotion.",
        methods: [
          {
            method: "PATCH",
            access: "Admin",
            request: "Route param `id`, body = UpdatePromotionDto",
            response: "ApiEnvelope<PromotionRecord>",
            notes: "Synchronizes scope definitions during updates.",
          },
          {
            method: "DELETE",
            access: "Admin",
            request: "Route param `id`",
            response: "ApiEnvelope<{ deleted: boolean }>",
            notes: "Used by the promotion registry page.",
          },
        ],
      },
      {
        path: "/api/admin/inventory/movements",
        source: "app/api/admin/inventory/movements/route.ts",
        summary: "Paginated inventory movement ledger.",
        methods: [
          {
            method: "GET",
            access: "Admin",
            request: "Query = StockMovementsQuery",
            response:
              "ApiEnvelope<StockMovementListResult> with pagination meta",
            notes:
              "Tracks adjustments, reservations, releases, and stock consumption.",
          },
        ],
      },
      {
        path: "/api/admin/inventory/low-stock",
        source: "app/api/admin/inventory/low-stock/route.ts",
        summary: "Variants below an admin-supplied stock threshold.",
        methods: [
          {
            method: "GET",
            access: "Admin",
            request: "Query = LowStockQuery",
            response: "ApiEnvelope<LowStockVariantResult> with pagination meta",
            notes: "Use this to drive replenishment workflows.",
          },
        ],
      },
      {
        path: "/api/admin/inventory/adjust",
        source: "app/api/admin/inventory/adjust/route.ts",
        summary: "Manual stock adjustments with actor and reason tracking.",
        methods: [
          {
            method: "POST",
            access: "Admin",
            request: "Body = AdjustStockDto",
            response: "ApiEnvelope<InventoryAdjustmentResult>",
            notes: "Creates stock movement entries and audit records.",
          },
        ],
      },
      {
        path: "/api/admin/settings",
        source: "app/api/admin/settings/route.ts",
        summary: "Read or bulk update runtime store settings.",
        methods: [
          {
            method: "GET",
            access: "Admin",
            request: "No body",
            response: "ApiEnvelope<AdminStoreConfigSnapshot>",
            notes:
              "Settings page data source, including missing-default detection.",
          },
          {
            method: "PATCH",
            access: "Admin",
            request: "Body = BulkUpdateStoreConfigDto",
            response:
              "ApiEnvelope<{ updatedCount: number; createdCount: number }>",
            notes:
              "Each successful change is also written into audit history.",
          },
        ],
      },
      {
        path: "/api/admin/settings/initialize",
        source: "app/api/admin/settings/initialize/route.ts",
        summary: "Restore missing default settings into the database.",
        methods: [
          {
            method: "POST",
            access: "Admin",
            request: "No body",
            response: "ApiEnvelope<{ createdCount: number }>",
            notes: "Useful after first bootstrap or key expansion.",
          },
        ],
      },
      {
        path: "/api/admin/audit",
        source: "app/api/admin/audit/route.ts",
        summary: "Filtered audit log search across operations and domains.",
        methods: [
          {
            method: "GET",
            access: "Admin",
            request: "Query = AuditLogListQuery",
            response: "ApiEnvelope<AuditLogListResult> with pagination meta",
            notes:
              "Supports action, actor, entity, context, and free-text filters.",
          },
        ],
      },
    ],
  },
];

export const serverModules: ServerModuleDoc[] = [
  {
    title: "Auth",
    path: "src/server/auth/service.ts",
    summary: "Cookie-first session flows, user guards, and profile updates.",
    functions: [
      {
        name: "registerUser",
        signature: "registerUser(dto: RegisterDto)",
        notes:
          "Creates a customer, hashes the password, and returns session payload data.",
      },
      {
        name: "loginUser",
        signature: "loginUser(dto: LoginDto)",
        notes: "Authenticates credentials and resolves a normalized auth user payload.",
      },
      {
        name: "getCurrentUser / requireUser / requireAdminUser",
        signature:
          "getCurrentUser(request), requireUser(request), requireAdminUser(request)",
        notes:
          "Use these in route handlers, server components, and admin guards.",
      },
      {
        name: "updateUserProfile",
        signature: "updateUserProfile(userId: string, dto: UpdateProfileDto)",
        notes:
          "Mutates supported profile fields without duplicating auth logic in UI.",
      },
    ],
  },
  {
    title: "Catalog",
    path: "src/server/catalog/service.ts",
    summary: "Public and admin catalog reads plus category and product mutations.",
    functions: [
      {
        name: "listProducts / getPublicProductBySlug",
        signature:
          "listProducts(query: ProductListQuery), getPublicProductBySlug(slug: string)",
        notes: "Storefront-facing reads for listings and detail pages.",
      },
      {
        name: "listAdminProducts / getAdminProductById",
        signature:
          "listAdminProducts(query: ProductListQuery), getAdminProductById(id: string)",
        notes: "Admin-facing reads with richer variant and option detail.",
      },
      {
        name: "createProduct / updateProduct / deleteProduct",
        signature: "createProduct(dto), updateProduct(id, dto), deleteProduct(id)",
        notes:
          "Includes option definitions, option values, SKU validation, and variant combination persistence.",
      },
      {
        name: "Category functions",
        signature:
          "listPublicCategories, listAdminCategories, createCategory, updateCategory, deleteCategory",
        notes:
          "Use the same module for storefront filters and admin maintenance.",
      },
    ],
  },
  {
    title: "Cart",
    path: "src/server/cart/service.ts",
    summary: "Guest or authenticated active cart lifecycle with stock validation.",
    functions: [
      {
        name: "getOrCreateActiveCart",
        signature: "getOrCreateActiveCart(identity: CartIdentity)",
        notes:
          "Creates a cart on first access and returns a normalized snapshot.",
      },
      {
        name: "Cart mutations",
        signature:
          "addCartItem, updateCartItem, removeCartItem, clearActiveCart",
        notes:
          "These functions are the single source of truth for cart behavior.",
      },
      {
        name: "claimGuestCart",
        signature: "claimGuestCart(userId: string, guestToken: string)",
        notes:
          "Merges guest cart state into the authenticated customer cart during login or register.",
      },
    ],
  },
  {
    title: "Checkout and Orders",
    path: "src/server/checkout/service.ts and src/server/orders/service.ts",
    summary:
      "Quote building, checkout preview, transactional order placement, and order lifecycle control.",
    functions: [
      {
        name: "buildCheckoutQuote / getCheckoutPreview",
        signature:
          "buildCheckoutQuote(identity, dto, db?), getCheckoutPreview(identity, dto)",
        notes:
          "The preview and final order flow share the same quote engine to avoid drift.",
      },
      {
        name: "placeOrder",
        signature:
          "placeOrder(userId: string, dto: PlaceOrderDto, idempotencyKey?: string)",
        notes:
          "Creates order, payment, stock reservations, promotion usage, and audit records in one transaction.",
      },
      {
        name: "Customer order reads",
        signature: "listMyOrders(userId, query), getMyOrderById(orderId, userId)",
        notes: "Owner-scoped storefront order history and detail.",
      },
      {
        name: "Admin order operations",
        signature:
          "listAdminOrders(query), getAdminOrderById(orderId), updateOrderStatus(orderId, dto, actorId)",
        notes:
          "Used for fulfillment, payment synchronization, and state transitions.",
      },
    ],
  },
  {
    title: "Payments and Promotions",
    path: "src/server/payments/service.ts and src/server/promotions/service.ts",
    summary: "Manual payment review plus promotion and voucher logic.",
    functions: [
      {
        name: "Payment functions",
        signature:
          "getPaymentInstructions, uploadPaymentProof, listAdminPaymentReviewQueue, getAdminPaymentById, reviewPayment",
        notes:
          "Confirms or rejects proofs while synchronizing parent order state.",
      },
      {
        name: "Promotion functions",
        signature:
          "validateVoucherSelection, validateVoucherCodes, listAdminPromotions, createPromotion, updatePromotion, deletePromotion",
        notes:
          "Supports scope-aware validation, usage limits, and `FREE_PRODUCT` discounting.",
      },
    ],
  },
  {
    title: "Inventory, Settings, Audit",
    path: "src/server/inventory/service.ts, settings/service.ts, audit/service.ts",
    summary:
      "Operational admin modules for stock, runtime config, and traceability.",
    functions: [
      {
        name: "Inventory functions",
        signature:
          "adjustStock, listStockMovements, listLowStockVariants",
        notes:
          "Tracks actor ids, reference ids, and negative-stock guards.",
      },
      {
        name: "Settings functions",
        signature:
          "listAdminStoreConfigs, initializeMissingStoreConfigs, bulkUpdateStoreConfigs",
        notes:
          "Runtime configuration is loaded from here, not from ad hoc client constants.",
      },
      {
        name: "Audit function",
        signature: "listAdminAuditLogs(query: AuditLogListQuery)",
        notes:
          "Generic polymorphic audit log design stays centralized instead of per-entity audit tables.",
      },
    ],
  },
  {
    title: "Addresses, Users, Dashboard, Store Config",
    path: "src/server/addresses, users, dashboard, and store-config",
    summary:
      "Supporting modules that feed profile, admin registry, dashboard metrics, and runtime configuration.",
    functions: [
      {
        name: "Address functions",
        signature:
          "listMyAddresses, createAddress, updateAddress, deleteAddress",
        notes:
          "Saved address management with default-address behavior.",
      },
      {
        name: "Users and dashboard functions",
        signature:
          "listAdminUsers, getAdminUserCounts, getAdminDashboardSummary",
        notes: "Admin reporting and registry reads.",
      },
      {
        name: "Store config runtime functions",
        signature:
          "getStoreConfigSnapshot, getStoreRuntimeConfig, getStoreConfigNumberValue, getStoreConfigTextValue, getStoreConfigBooleanValue",
        notes:
          "Typed accessors for runtime config consumed by checkout, layouts, and payment instructions.",
      },
    ],
  },
];

export const domainHelpers: ServerFunctionDoc[] = [
  {
    name: "getEffectivePrice",
    signature: "getEffectivePrice(product, variant)",
    notes:
      "Resolves the final unit price from variant override, product promo price, or product base price.",
  },
  {
    name: "isValidStatusTransition",
    signature: "isValidStatusTransition(from: OrderStatus, to: OrderStatus)",
    notes:
      "Centralized order state machine guard used by admin order updates and payment review synchronization.",
  },
  {
    name: "isPromotionEligible",
    signature: "isPromotionEligible(promotion, now?, userUsageCount?)",
    notes:
      "Checks active window, total usage cap, and per-user usage cap before a promotion can apply.",
  },
  {
    name: "calculateDiscount",
    signature: "calculateDiscount(promotion, subtotal)",
    notes:
      "Computes percentage or fixed-amount discount values. `FREE_PRODUCT` and `FREE_SHIPPING` are handled elsewhere in promo orchestration.",
  },
  {
    name: "calculateShipping",
    signature:
      "calculateShipping({ subtotalAfterDiscount, freeShippingThreshold, flatShippingCost, hasFreeShippingVoucher }, etaDays?)",
    notes:
      "Internal flat-rate shipping helper honoring threshold-based free shipping and voucher-driven free shipping.",
  },
  {
    name: "checkStockAvailability",
    signature: "checkStockAvailability(items)",
    notes:
      "Returns an availability summary based on stock-on-hand and active reservations, used by cart and order flows.",
  },
];

export const hooks: HookDoc[] = [
  {
    name: "useCart",
    path: "src/hooks/use-cart.ts",
    summary:
      "Client hook for local cart mutation workflows with optional SSR-provided initial state.",
    returns: [
      "cart",
      "items",
      "itemCount",
      "subtotal",
      "isLoading",
      "error",
      "refreshCart()",
      "addItem(dto)",
      "updateQty({ itemId, qty })",
      "removeItem(itemId)",
      "clearCart()",
    ],
  },
  {
    name: "useSession",
    path: "src/hooks/use-session.ts",
    summary:
      "SSR-safe auth/session hook for client surfaces that still need session awareness after hydration.",
    returns: [
      "session",
      "isLoading",
      "isAuthenticated",
      "error",
      "refreshSession()",
      "setSession(session)",
      "clearSession()",
    ],
  },
];

export const clientHelpers: ClientHelperDoc[] = [
  {
    title: "Auth Client",
    path: "src/lib/auth/client.ts",
    summary: "Same-origin helpers for login, register, logout, and session fetch.",
    functions: [
      "loginRequest",
      "registerRequest",
      "logoutRequest",
      "getSessionRequest",
    ],
  },
  {
    title: "Cart Client",
    path: "src/lib/cart/client.ts",
    summary: "Thin wrappers around cart route handlers.",
    functions: [
      "fetchCart",
      "addItemToCart",
      "updateCartItemQty",
      "removeCartItemById",
      "clearCart",
    ],
  },
  {
    title: "Checkout Client",
    path: "src/lib/checkout/client.ts",
    summary: "Preview-only helper for live checkout quote refreshes.",
    functions: ["fetchCheckoutPreview"],
  },
  {
    title: "Orders Client",
    path: "src/lib/orders/client.ts",
    summary: "Helpers for place-order and admin order status updates.",
    functions: ["placeOrderRequest", "updateAdminOrderStatusRequest"],
  },
  {
    title: "Payments Client",
    path: "src/lib/payments/client.ts",
    summary: "Helpers for customer proof upload and admin payment review actions.",
    functions: ["uploadPaymentProofRequest", "reviewPaymentRequest"],
  },
  {
    title: "Promotions Client",
    path: "src/lib/promotions/client.ts",
    summary: "Admin promotion mutation helpers.",
    functions: [
      "createPromotionRequest",
      "updatePromotionRequest",
      "deletePromotionRequest",
    ],
  },
  {
    title: "Settings Client",
    path: "src/lib/settings/client.ts",
    summary: "Admin store settings mutation helpers.",
    functions: [
      "updateStoreSettingsRequest",
      "initializeStoreSettingsRequest",
    ],
  },
  {
    title: "Profile Client",
    path: "src/lib/profile/client.ts",
    summary: "Read and update the currently authenticated profile record.",
    functions: ["getMyProfileRequest", "updateMyProfileRequest"],
  },
  {
    title: "Addresses Client",
    path: "src/lib/addresses/client.ts",
    summary: "Customer address CRUD helpers.",
    functions: [
      "listMyAddressesRequest",
      "createAddressRequest",
      "updateAddressRequest",
      "deleteAddressRequest",
    ],
  },
  {
    title: "Products Client",
    path: "src/lib/products/client.ts",
    summary: "Admin product mutation helpers for the editor experience.",
    functions: [
      "createProductRequest",
      "updateProductRequest",
      "deleteProductRequest",
    ],
  },
  {
    title: "Categories Client",
    path: "src/lib/categories/client.ts",
    summary: "Admin category mutation helpers.",
    functions: [
      "createCategoryRequest",
      "updateCategoryRequest",
      "deleteCategoryRequest",
    ],
  },
  {
    title: "Cross-cutting Utilities",
    path: "src/lib/formatters.ts, src/lib/search-params.ts, src/lib/user-facing-error.ts",
    summary: "Formatting, query param normalization, and UI-safe error message helpers.",
    functions: [
      "formatCurrency",
      "formatDateTime",
      "getSingleSearchParamValue",
      "toFlatSearchParams",
      "toUserFacingErrorMessage",
    ],
  },
];

export const contractGroups: ContractGroupDoc[] = [
  {
    title: "Auth and User DTOs",
    path: "src/shared/contracts/dto/auth.dto.ts",
    summary: "Account lifecycle, profile mutation, and user list query shapes.",
    items: ["RegisterDto", "LoginDto", "UpdateProfileDto", "UserListQuery"],
  },
  {
    title: "Cart DTOs",
    path: "src/shared/contracts/dto/cart.dto.ts",
    summary: "Cart mutation inputs and normalized cart snapshot output.",
    items: ["AddCartItemDto", "UpdateCartItemDto", "CartSnapshot"],
  },
  {
    title: "Order and Checkout DTOs",
    path: "src/shared/contracts/dto/order.dto.ts",
    summary: "Preview, placement, listing, and status transition contracts.",
    items: [
      "CheckoutPreviewDto",
      "CheckoutPreviewResult",
      "PlaceOrderDto",
      "OrderListQuery",
      "UpdateOrderStatusDto",
    ],
  },
  {
    title: "Payment DTOs",
    path: "src/shared/contracts/dto/payment.dto.ts",
    summary: "Payment methods, statuses, proof upload, review decisions, and review queue query shapes.",
    items: [
      "UploadPaymentProofDto",
      "ReviewPaymentDto",
      "PaymentInstructions",
      "PaymentReviewQueueQuery",
    ],
  },
  {
    title: "Catalog DTOs",
    path: "src/shared/contracts/dto/product.dto.ts and category.dto.ts",
    summary: "Product queries, product mutations, and category mutations.",
    items: [
      "ProductListQuery",
      "CreateProductDto",
      "UpdateProductDto",
      "CreateCategoryDto",
      "UpdateCategoryDto",
    ],
  },
  {
    title: "Promotion DTOs",
    path: "src/shared/contracts/dto/promotion.dto.ts",
    summary: "Promotion CRUD, scope configuration, and voucher validation input.",
    items: [
      "CreatePromotionDto",
      "UpdatePromotionDto",
      "ValidateVoucherDto",
      "PromotionListQuery",
    ],
  },
  {
    title: "Inventory DTOs",
    path: "src/shared/contracts/dto/inventory.dto.ts",
    summary: "Inventory adjustment and reporting query shapes.",
    items: ["AdjustStockDto", "StockMovementsQuery", "LowStockQuery"],
  },
  {
    title: "Settings, Audit, and Address DTOs",
    path: "src/shared/contracts/dto/store-config.dto.ts, audit.dto.ts, address.dto.ts",
    summary: "Store config updates, audit filters, and customer address records.",
    items: [
      "BulkUpdateStoreConfigDto",
      "AuditLogListQuery",
      "CreateAddressDto",
      "UpdateAddressDto",
      "AddressRecord",
    ],
  },
  {
    title: "API Envelope and Errors",
    path: "src/shared/contracts/envelopes.ts and error-codes.ts",
    summary: "Consistent response envelope and shared error code registry.",
    items: ["ApiEnvelope<T>", "successResponse", "errorResponse", "ErrorCodes"],
  },
  {
    title: "Route Param Validation",
    path: "src/shared/contracts/route-params.ts",
    summary: "Shared validation for dynamic App Router params such as ids, slugs, and nested route tokens.",
    items: [
      "Validated route params for orderId, itemId, paymentId, product id, and category id",
    ],
  },
];

export const codeExamples: CodeExampleDoc[] = [
  {
    title: "Server-side checkout preview",
    language: "ts",
    description:
      "Use server modules directly in a Server Component, Route Handler, or Server Action when you want to avoid client-side duplication.",
    code: `import { getCheckoutPreview } from "@/server";

export async function loadPreview(userId: string) {
  return getCheckoutPreview(
    { userId },
    {
      shippingMethod: "INTERNAL_FLAT",
      voucherCodes: ["WELCOME10"],
    },
  );
}`,
  },
  {
    title: "Client-side cart hook",
    language: "tsx",
    description:
      "Use \`useCart\` when the UI needs live cart mutation after hydration. Pass the SSR cart snapshot when available.",
    code: `"use client";

import { useCart } from "@/hooks";

export function AddToCartButton(props: {
  productId: string;
  productVariantId: string;
}) {
  const { addItem, itemCount, isLoading } = useCart();

  return (
    <button
      disabled={isLoading}
      onClick={() =>
        void addItem({
          productId: props.productId,
          productVariantId: props.productVariantId,
          qty: 1,
        })
      }
    >
      Add to cart ({itemCount})
    </button>
  );
}`,
  },
  {
    title: "Place an order with idempotency",
    language: "ts",
    description:
      "The order route accepts an idempotency key header. Reuse the same key to safely retry the same checkout intent.",
    code: `import { placeOrderRequest } from "@/lib/orders/client";

const idempotencyKey = crypto.randomUUID();

await placeOrderRequest(
  {
    shippingMethod: "INTERNAL_FLAT",
    paymentMethod: "MANUAL_TRANSFER",
    voucherCodes: ["WELCOME10"],
    shippingAddress: {
      recipientName: "Jane Doe",
      phone: "+628123456789",
      addressLine1: "Jl. Example No. 10",
      city: "Jakarta",
    },
  },
  idempotencyKey,
);`,
  },
];

export const envelopeExample = `{
  "success": true,
  "data": {
    "id": "cmfexample123",
    "orderNumber": "ORD-202603100001-AB12CD"
  },
  "error": null
}`;

export const operationsNotes: string[] = [
  "All mutating API routes assume same-origin deployment and enforce cookie-safe request handling.",
  "Session auth is stored in an httpOnly cookie, not in localStorage or client-side bearer storage.",
  "Customer-owned resources such as orders, payment instructions, proofs, and addresses are scoped on the server.",
  "CSRF-style origin checks run for mutating `/api/*` requests that rely on cookies.",
  "Prisma is the only live data layer. Avoid duplicating persistence logic outside `src/server`.",
  "Current automated verification baseline is `npm test`, `npm run test:e2e`, `npm run lint`, `npm run typecheck`, and `npm run build`.",
];

const apiEndpointCount = apiDomains.reduce(
  (sum, domain) => sum + domain.endpoints.length,
  0,
);
const serverModuleCount = serverModules.length;
const clientHelperFunctionCount = clientHelpers.reduce(
  (sum, helper) => sum + helper.functions.length,
  0,
);

export const developerDocsStats: DeveloperDocsStat[] = [
  {
    label: "API Paths",
    value: String(apiEndpointCount),
    description:
      "Documented route handler paths grouped by domain and access level.",
  },
  {
    label: "Server Modules",
    value: String(serverModuleCount),
    description:
      "Reusable business modules that should stay stable across storefront projects.",
  },
  {
    label: "Hooks",
    value: String(hooks.length),
    description:
      "Client hooks kept intentionally thin for local UI and mutation flows.",
  },
  {
    label: "Client Helpers",
    value: String(clientHelperFunctionCount),
    description:
      "Named request helpers that connect UI surfaces to same-origin route handlers.",
  },
];
